service: my-app

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    AMADEUS_CLIENT_ID: "IA564C4s6ciTyZ4WAF5JI9K4K0"
    AMADEUS_CLIENT_SECRET: "botcysSSVZYQm"
  timeout: 15

functions:
  helloworld:
    handler: handler.run
    events:
      - http:
          path: /
          method: get

  getAllTodos:
    handler: getAllTodos.run
    events:
      - http:
          path: todos
          method: get

  getTodo:
    handler: getTodo.run
    events:
      - http:
          path: todos/{id}
          method: get

  createTodos:
    handler: create.run
    events:
      - http:
          path: todos
          method: post

  api:
    handler: src/lamda.handler
    events:
      - http:
          path: /{greedy+}
          method: ANY

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
